name: flab test
on: 
  push:
    branches:
      - develop
env:
  APP_ENV: test

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    services:
#      mysql:
#        image: mysql:8.0
#        ports:
#          - 3306:3306
#        env:
##          MYSQL_DATABASE: test
##          MYSQL_ROOT_PASSWORD: dltjdrnr3137
##          MYSQL_USER: admin
##          MYSQL_PASSWORD: dltjdrnr3137
#          MYSQL_DATABASE: ${{secrets.MYSQL_DATABASE}}
#          MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD}}
#          MYSQL_USER: ${{secrets.MYSQL_USER}}
#          MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
#        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

#      - uses: shogo82148/actions-setup-mysql@v1
#        with:
#          mysql-version: "8.0"
#      - run: mysql -uroot -e 'create database test'


      - uses: mirromutth/mysql-action@v1.1
        with:
#          host port: 3800 # Optional, default value is 3306. The port of host
#          container port: 3307 # Optional, default value is 3306. The port of container
          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
          mysql database: 'test' # Optional, default value is "test". The specified database which will be create
          mysql root password: ${{ secrets.MYSQL_ROOT_PASSWORD }} # Required if "mysql user" is empty, default is empty. The root superuser password
          mysql user: 'admin' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: ${{secrets.MYSQL_PASSWORD}} # Required if "mysql user" exists. The password for the "mysql user"

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: virtual activate
        run: |
          source .venv/bin/activate

      - name: cryptography
        run: poetry add cryptography

      - name: black check
        run: poetry run black flab_bada/ --line-length=127

      - name: flake8 check
        run: poetry run flake8 flab_bada/ --max-line-length=127

      - name: alembic upgrade
        run: poetry run alembic upgrade head

      - name: Test with pytest
        run: poetry run pytest -v -W ignore::DeprecationWarning
      
  
